# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

def shared_pods
  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
#   pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
# #   pod 'React', path: '../node_modules/react-native'
#   pod 'React', :path => '../node_modules/react-native', :subspecs => [
#     'Core',
#     'CxxBridge',
#     'DevSupport',
#     'RCTActionSheet',
#     'RCTAnimation',
#     'RCTGeolocation',
#     'RCTImage',
#     'RCTLinkingIOS',
#     'RCTNetwork',
#     'RCTSettings',
#     'RCTText',
#     'RCTVibration',
#     'RCTWebSocket',
#   ]
end

target 'BCAutoFillExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BCAutoFillExtension
  shared_pods
end

target 'Buttercup' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Buttercup
  shared_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
  end
