require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Buttercup' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'ButtercupTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
end

target 'BCAutoFillExtension' do
    config = use_native_modules!

    # use_react_native!(
    #     :path => config[:reactNativePath],
    #     # to enable hermes on iOS, change `false` to `true` and then install pods
    #     :hermes_enabled => false
    # )

    use_flipper!()
end

post_install do |installer|
    [
        'boost-for-react-native',
        'Flipper-DoubleConversion',
        'Flipper-Glog',
        'Flipper-PeerTalk',
        'RNReactNativeSharedGroupPreferences',
        'RNSecureStorage',
        'TouchID',
        'YogaKit'
    ].each do |podName|
        t = installer.pods_project.targets.find { |t| t.name == podName }
        t.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
            # config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        end
    end
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
            config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        end
    end
    # t = installer.pods_project.targets.find { |t| t.name == 'RNSecureStorage' }
    # t.build_configurations.each do |bc|
    #   bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    # end
    react_native_post_install(installer)
end
